/*
 * Generated by scripts/build-admin.js.
 * Edit js/admin-*.js source modules, then run npm run build:admin.
 */

// ---- admin-core.js ----
const DEFAULT_IMAGE = "imagenes/optimized/productos/productos-1.webp";
const PRODUCT_IMAGES_BUCKET = "product-images";
const BRAND_LOGOS_BUCKET = "brand-logos";
const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
const MAX_PRODUCT_IMAGE_SIZE = 4 * 1024 * 1024;
const MAX_BRAND_LOGO_SIZE = 2 * 1024 * 1024;

let products = [];
let brands = [];
let categories = [];
let subcategories = [];
let contactLeads = [];
let stockMovements = [];
let currentUser = null;
let selectedProductFile = null;
let selectedBrandFile = null;
let adminProductPage = 1;
let adminProductPageSize = 25;
let adminProductSort = "created_desc";

const ADMIN_PRODUCTS_PER_PAGE = 25;

const menuButtons = document.querySelectorAll("[data-section]");
const sections = document.querySelectorAll(".admin-section");
const sectionTitle = document.getElementById("section-title");
const sectionDescription = document.getElementById("section-description");

const form = document.getElementById("product-form");
const list = document.getElementById("product-list");
const productPagination = document.getElementById("product-pagination");
const stockList = document.getElementById("stock-list");
const brandsList = document.getElementById("brands-list");
const categoriesList = document.getElementById("categories-list");
const subcategoriesList = document.getElementById("subcategories-list");
const leadsList = document.getElementById("leads-list");
const leadSearch = document.getElementById("lead-search");
const leadStatusFilter = document.getElementById("lead-status-filter");
const leadsNotice = document.getElementById("leads-notice");
const stockMovementForm = document.getElementById("stock-movement-form");
const stockMovementNotice = document.getElementById("stock-movement-notice");
const stockMovementProduct = document.getElementById("stock-movement-product");
const stockMovementType = document.getElementById("stock-movement-type");
const stockMovementQuantity = document.getElementById("stock-movement-quantity");
const stockMovementNote = document.getElementById("stock-movement-note");
const stockMovementList = document.getElementById("stock-movement-list");

const search = document.getElementById("admin-search");
const brandFilter = document.getElementById("brand-filter");
const categoryFilter = document.getElementById("category-filter");
const subcategoryFilter = document.getElementById("subcategory-filter");
const stockFilter = document.getElementById("stock-filter");
const productPageSize = document.getElementById("product-page-size");
const productSort = document.getElementById("product-sort");
const notice = document.getElementById("notice");
const formTitle = document.getElementById("form-title");
const saveBtn = document.getElementById("save-btn");
const resetBtn = document.getElementById("reset-btn");
const logoutBtn = document.getElementById("logout-btn");
const adminModal = document.getElementById("admin-modal");
const adminModalTitle = document.getElementById("admin-modal-title");
const adminModalMessage = document.getElementById("admin-modal-message");
const adminModalCancel = document.getElementById("admin-modal-cancel");
const adminModalConfirm = document.getElementById("admin-modal-confirm");

const imagePreview = document.getElementById("image-preview");
const productFileInput = document.getElementById("product-file");
const uploadStatus = document.getElementById("upload-status");

const brandFileInput = document.getElementById("brand-file");
const brandUploadStatus = document.getElementById("brand-upload-status");

const statProducts = document.getElementById("stat-products");
const statBrands = document.getElementById("stat-brands");
const statCategories = document.getElementById("stat-categories");
const statSubcategories = document.getElementById("stat-subcategories");

const fields = {
  id: document.getElementById("product-id"),
  name: document.getElementById("product-name"),
  brand: document.getElementById("product-brand"),
  category: document.getElementById("product-category"),
  subcategory: document.getElementById("product-subcategory"),
  image: document.getElementById("product-image"),
  stock: document.getElementById("product-stock"),
  stockQuantity: document.getElementById("product-stock-quantity"),
  lowStock: document.getElementById("product-low-stock"),
  desc: document.getElementById("product-description"),
};

const brandForm = document.getElementById("brand-form");
const brandNotice = document.getElementById("brand-notice");
const brandFormTitle = document.getElementById("brand-form-title");
const brandSaveBtn = document.getElementById("brand-save-btn");
const brandResetBtn = document.getElementById("brand-reset-btn");

const brandFields = {
  id: document.getElementById("brand-id"),
  name: document.getElementById("brand-name"),
  logo: document.getElementById("brand-logo"),
  description: document.getElementById("brand-description"),
  sort: document.getElementById("brand-sort"),
  active: document.getElementById("brand-active"),
};

const categoryForm = document.getElementById("category-form");
const categoryNotice = document.getElementById("category-notice");
const categoryFormTitle = document.getElementById("category-form-title");
const categorySaveBtn = document.getElementById("category-save-btn");
const categoryResetBtn = document.getElementById("category-reset-btn");

const categoryFields = {
  id: document.getElementById("category-id"),
  name: document.getElementById("category-name"),
  description: document.getElementById("category-description"),
  icon: document.getElementById("category-icon"),
  sort: document.getElementById("category-sort"),
  active: document.getElementById("category-active"),
};

const subcategoryForm = document.getElementById("subcategory-form");
const subcategoryNotice = document.getElementById("subcategory-notice");
const subcategoryFormTitle = document.getElementById("subcategory-form-title");
const subcategorySaveBtn = document.getElementById("subcategory-save-btn");
const subcategoryResetBtn = document.getElementById("subcategory-reset-btn");

const subcategoryFields = {
  id: document.getElementById("subcategory-id"),
  name: document.getElementById("subcategory-name"),
  category: document.getElementById("subcategory-category"),
  description: document.getElementById("subcategory-description"),
  sort: document.getElementById("subcategory-sort"),
  active: document.getElementById("subcategory-active"),
};

const companyForm = document.getElementById("company-form");
const companyNotice = document.getElementById("company-notice");
const companySaveBtn = document.getElementById("company-save-btn");
const companyReloadBtn = document.getElementById("company-reload-btn");

const companyFields = {
  id: document.getElementById("company-id"),
  phone: document.getElementById("company-phone"),
  phoneRaw: document.getElementById("company-phone-raw"),
  email: document.getElementById("company-email"),
  address: document.getElementById("company-address"),
  hours: document.getElementById("company-hours"),
  whatsappUrl: document.getElementById("company-whatsapp-url"),
  mapUrl: document.getElementById("company-map-url"),
  mapEmbed: document.getElementById("company-map-embed"),
};

const companyPreview = {
  phone: document.getElementById("preview-company-phone"),
  email: document.getElementById("preview-company-email"),
  address: document.getElementById("preview-company-address"),
  hours: document.getElementById("preview-company-hours"),
};
const sectionInfo = {
  products: {
    title: "Gestión de productos",
    description: "Agrega, edita, elimina y revisa productos con imágenes en Supabase Storage.",
  },
  brands: {
    title: "Gestión de marcas",
    description: "Agrega, edita y elimina marcas guardadas en Supabase.",
  },
  categories: {
    title: "Gestión de categorías",
    description: "Agrega, edita y elimina categorías guardadas en Supabase.",
  },
  subcategories: {
    title: "Gestión de subcategorías",
    description: "Agrega, edita y elimina subcategorías relacionadas a cada categoría.",
  },
  stock: {
    title: "Gestión de stock",
    description: "Registra entradas, salidas y ajustes con historial por producto.",
  },
  company: {
    title: "Datos de empresa",
    description: "Edita teléfono, correo, dirección, horarios y enlaces principales de la empresa.",
  },
  leads: {
    title: "Leads de contacto",
    description: "Revisa las consultas enviadas desde la web.",
  },
  help: {
    title: "Ayuda y estado",
    description: "Resumen de conexión, base de datos y Storage.",
  },
};

function escapeHTML(text) {
  return cleanText(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function cleanText(text) {
  return String(text || "")
    .replace(/Ã¡/g, "á")
    .replace(/Ã©/g, "é")
    .replace(/Ã­/g, "í")
    .replace(/Ã³/g, "ó")
    .replace(/Ãº/g, "ú")
    .replace(/Ã±/g, "ñ")
    .replace(/Ã/g, "Á")
    .replace(/Ã‰/g, "É")
    .replace(/Ã/g, "Í")
    .replace(/Ã“/g, "Ó")
    .replace(/Ãš/g, "Ú")
    .replace(/Ã‘/g, "Ñ")
    .replace(/Â¿/g, "¿")
    .replace(/Â¡/g, "¡")
    .replace(/Â°/g, "°")
    .replace(/Â/g, "")
    .replace(/â€¦/g, "...")
    .replace(/â†’/g, "->");
}

function showNotice(element, text, type = "success") {
  element.textContent = text;
  element.className = `notice show ${type}`;

  setTimeout(() => {
    element.className = "notice";
    element.textContent = "";
  }, 3500);
}

function setUploadStatus(text, type = "") {
  uploadStatus.textContent = text;
  uploadStatus.className = type ? `upload-status ${type}` : "upload-status";
}

function setBrandUploadStatus(text, type = "") {
  brandUploadStatus.textContent = text;
  brandUploadStatus.className = type ? `upload-status ${type}` : "upload-status";
}

function getStockClass(stock) {
  const value = String(stock || "").toLowerCase();
  if (value.includes("sin")) return "unavailable";
  if (value.includes("pedido")) return "preorder";
  return "available";
}

function formatFileSize(bytes) {
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 MB";
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function validateImageFile(file, maxSize, label = "imagen") {
  if (!file) return null;

  if (!ALLOWED_IMAGE_TYPES.includes(file.type)) {
    return `El archivo debe ser JPG, PNG o WebP.`;
  }

  if (file.size > maxSize) {
    return `El ${label} supera ${formatFileSize(maxSize)}. Comprime el archivo antes de subirlo.`;
  }

  return null;
}

function showAdminDialog({
  title = "Confirmar acción",
  message = "",
  confirmText = "Aceptar",
  cancelText = "Cancelar",
  showCancel = true,
  danger = false,
} = {}) {
  return new Promise((resolve) => {
    adminModalTitle.textContent = title;
    adminModalMessage.textContent = message;
    adminModalConfirm.textContent = confirmText;
    adminModalCancel.textContent = cancelText;
    adminModalCancel.style.display = showCancel ? "" : "none";
    adminModalConfirm.className = danger ? "admin-btn admin-btn-danger" : "admin-btn admin-btn-primary";

    const close = (value) => {
      adminModal.classList.remove("show");
      adminModal.setAttribute("aria-hidden", "true");
      adminModalConfirm.removeEventListener("click", onConfirm);
      adminModalCancel.removeEventListener("click", onCancel);
      adminModal.removeEventListener("click", onBackdrop);
      document.removeEventListener("keydown", onKeydown);
      resolve(value);
    };

    const onConfirm = () => close(true);
    const onCancel = () => close(false);
    const onBackdrop = (event) => {
      if (event.target === adminModal) close(false);
    };
    const onKeydown = (event) => {
      if (event.key === "Escape") close(false);
    };

    adminModalConfirm.addEventListener("click", onConfirm);
    adminModalCancel.addEventListener("click", onCancel);
    adminModal.addEventListener("click", onBackdrop);
    document.addEventListener("keydown", onKeydown);

    adminModal.classList.add("show");
    adminModal.setAttribute("aria-hidden", "false");
    adminModalConfirm.focus();
  });
}

function showAdminAlert(title, message) {
  return showAdminDialog({
    title,
    message,
    confirmText: "Entendido",
    showCancel: false,
  });
}

function openSection(sectionName) {
  menuButtons.forEach((button) => {
    button.classList.toggle("active", button.dataset.section === sectionName);
  });

  sections.forEach((section) => {
    section.classList.toggle("active", section.id === `section-${sectionName}`);
  });

  sectionTitle.textContent = sectionInfo[sectionName].title;
  sectionDescription.textContent = sectionInfo[sectionName].description;
}

function updateStats() {
  const activeProducts = products.filter((product) => product.is_active !== false);

  statProducts.textContent = activeProducts.length;
  statBrands.textContent = brands.filter((brand) => brand.is_active !== false).length;
  statCategories.textContent = categories.filter((category) => category.is_active !== false).length;
  statSubcategories.textContent = subcategories.filter((subcategory) => subcategory.is_active !== false).length;
}

// ---- admin-components.js ----
function renderAdminEmptyState({ icon = "fa-box-open", title, message }) {
  return `
    <div class="empty-state-admin">
      <i class="fa-solid ${escapeHTML(icon)}"></i>
      <h3>${escapeHTML(title)}</h3>
      <p>${escapeHTML(message)}</p>
    </div>
  `;
}

function renderAdminTag({ icon, label, className = "" }) {
  return `
    <span class="admin-tag ${escapeHTML(className)}">
      ${icon ? `<i class="fa-solid ${escapeHTML(icon)}"></i>` : ""}
      ${escapeHTML(label)}
    </span>
  `;
}

function getNumberOrNull(value) {
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function renderAdminProductTableRow(product) {
  const image = product.image_url || DEFAULT_IMAGE;
  const quantity = getNumberOrNull(product.stock_quantity);
  const lowStock = getNumberOrNull(product.low_stock_threshold) || 0;
  const quantityLabel = quantity === null ? "Sin cantidad" : `${quantity} und.`;
  const isLowStock = quantity !== null && quantity > 0 && lowStock > 0 && quantity <= lowStock;

  return `
    <tr>
      <td>
        <div class="table-product-cell">
          <img src="${escapeHTML(image)}" alt="${escapeHTML(product.name)}" />
          <div>
            <strong>${escapeHTML(product.name || "Producto sin nombre")}</strong>
            <small>${escapeHTML(product.description || "Sin descripcion registrada.")}</small>
          </div>
        </div>
      </td>

      <td>
        ${renderAdminTag({ icon: "fa-tag", label: product.brand || "Sin marca" })}
      </td>

      <td>
        <div class="table-meta">
          ${renderAdminTag({ icon: "fa-layer-group", label: product.category || "Sin categoria" })}
          ${product.subcategory ? `<span class="table-muted"><i class="fa-solid fa-sitemap"></i> ${escapeHTML(product.subcategory)}</span>` : ""}
        </div>
      </td>

      <td>
        <div class="table-meta">
          ${renderAdminTag({
            label: product.stock_status || "Disponible",
            className: `stock-tag ${getStockClass(product.stock_status)}`,
          })}
          <span class="table-muted ${isLowStock ? "low-stock-warning" : ""}">
            <i class="fa-solid fa-boxes-stacked"></i> ${escapeHTML(quantityLabel)}
          </span>
          ${isLowStock ? `<span class="table-muted low-stock-warning"><i class="fa-solid fa-triangle-exclamation"></i> Bajo stock</span>` : ""}
        </div>
      </td>

      <td>
        <div class="table-actions">
          <button class="icon-action" type="button" data-edit="${escapeHTML(product.id)}" title="Editar producto">
            <i class="fa-solid fa-pen"></i>
          </button>

          <button class="icon-action danger" type="button" data-delete="${escapeHTML(product.id)}" title="Eliminar producto">
            <i class="fa-solid fa-trash"></i>
          </button>
        </div>
      </td>
    </tr>
  `;
}

function renderSortButton(field, label) {
  const direction = adminProductSort === `${field}_asc` ? "desc" : "asc";
  const active = adminProductSort.startsWith(`${field}_`);
  const icon = active && adminProductSort.endsWith("_asc") ? "fa-arrow-up-a-z" : "fa-arrow-down-z-a";

  return `
    <button class="sort-btn ${active ? "active" : ""}" type="button" data-product-sort="${escapeHTML(field)}_${direction}">
      ${escapeHTML(label)} <i class="fa-solid ${escapeHTML(icon)}"></i>
    </button>
  `;
}

function renderAdminProductTable(productsToRender) {
  return `
    <div class="admin-table-wrap">
      <table class="admin-table">
        <thead>
          <tr>
            <th>${renderSortButton("name", "Producto")}</th>
            <th>${renderSortButton("brand", "Marca")}</th>
            <th>${renderSortButton("category", "Categoria")}</th>
            <th>${renderSortButton("stock", "Stock")}</th>
            <th style="text-align:right;">Acciones</th>
          </tr>
        </thead>
        <tbody>
          ${productsToRender.map(renderAdminProductTableRow).join("")}
        </tbody>
      </table>
    </div>
  `;
}

function renderAdminProductPagination({ totalProducts, start, shownProducts, totalPages }) {
  if (totalProducts === 0) return "";

  const from = start + 1;
  const to = start + shownProducts;

  return `
    <div class="admin-pagination">
      <span>Mostrando ${from}-${to} de ${totalProducts} productos</span>
      <div class="admin-pagination-actions">
        <label class="pagination-control">
          Ver
          <select data-product-page-size>
            <option value="25" ${adminProductPageSize === 25 ? "selected" : ""}>25</option>
            <option value="50" ${adminProductPageSize === 50 ? "selected" : ""}>50</option>
            <option value="100" ${adminProductPageSize === 100 ? "selected" : ""}>100</option>
          </select>
        </label>
        <button class="pagination-btn" type="button" data-product-page="prev" ${adminProductPage === 1 ? "disabled" : ""}>
          <i class="fa-solid fa-angle-left"></i> Anterior
        </button>
        <span>Pagina ${adminProductPage} de ${totalPages}</span>
        <button class="pagination-btn" type="button" data-product-page="next" ${adminProductPage === totalPages ? "disabled" : ""}>
          Siguiente <i class="fa-solid fa-angle-right"></i>
        </button>
      </div>
    </div>
  `;
}

// ---- admin-products.js ----
function renderProductFilters() {
  const activeBrands = brands
    .filter((brand) => brand.is_active !== false)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  const activeCategories = categories
    .filter((category) => category.is_active !== false)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  const activeSubcategories = subcategories
    .filter((subcategory) => subcategory.is_active !== false)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  const selectedBrand = brandFilter.value || "all";
  const selectedCategory = categoryFilter.value || "all";
  const selectedSubcategory = subcategoryFilter.value || "all";

  brandFilter.innerHTML =
    '<option value="all">Todas las marcas</option>' +
    activeBrands.map((brand) => `<option value="${escapeHTML(brand.id)}">${escapeHTML(brand.name)}</option>`).join("");

  categoryFilter.innerHTML =
    '<option value="all">Todas las categorías</option>' +
    activeCategories
      .map((category) => `<option value="${escapeHTML(category.id)}">${escapeHTML(category.name)}</option>`)
      .join("");

  subcategoryFilter.innerHTML =
    '<option value="all">Todas las subcategorías</option>' +
    activeSubcategories
      .map((subcategory) => `<option value="${escapeHTML(subcategory.id)}">${escapeHTML(subcategory.name)}</option>`)
      .join("");

  brandFilter.value = activeBrands.some((brand) => brand.id === selectedBrand) ? selectedBrand : "all";
  categoryFilter.value = activeCategories.some((category) => category.id === selectedCategory)
    ? selectedCategory
    : "all";
  subcategoryFilter.value = activeSubcategories.some((subcategory) => subcategory.id === selectedSubcategory)
    ? selectedSubcategory
    : "all";
}

function renderProductSelectors(selectedBrandId = "", selectedCategoryId = "", selectedSubcategoryId = "") {
  const activeBrands = brands
    .filter((brand) => brand.is_active !== false)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  const activeCategories = categories
    .filter((category) => category.is_active !== false)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  fields.brand.innerHTML =
    '<option value="">Selecciona una marca</option>' +
    activeBrands.map((brand) => `<option value="${escapeHTML(brand.id)}">${escapeHTML(brand.name)}</option>`).join("");

  fields.category.innerHTML =
    '<option value="">Selecciona una categoría</option>' +
    activeCategories
      .map((category) => `<option value="${escapeHTML(category.id)}">${escapeHTML(category.name)}</option>`)
      .join("");

  fields.brand.value = selectedBrandId || "";
  fields.category.value = selectedCategoryId || "";

  renderSubcategoryProductSelector(selectedCategoryId, selectedSubcategoryId);
}

function renderSubcategoryProductSelector(categoryId = "", selectedSubcategoryId = "") {
  const filteredSubcategories = subcategories
    .filter((subcategory) => subcategory.is_active !== false)
    .filter((subcategory) => !categoryId || subcategory.category_id === categoryId)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  // Si no hay categoría seleccionada, mostrar todas con el nombre de categoría entre paréntesis
  const showCategoryHint = !categoryId;

  fields.subcategory.innerHTML =
    '<option value="">Selecciona una subcategoría</option>' +
    filteredSubcategories
      .map((subcategory) => {
        const catName = showCategoryHint ? categories.find((c) => c.id === subcategory.category_id)?.name || "" : "";
        const label = catName
          ? `${escapeHTML(subcategory.name)} (${escapeHTML(catName)})`
          : escapeHTML(subcategory.name);
        return `<option value="${escapeHTML(subcategory.id)}">${label}</option>`;
      })
      .join("");

  fields.subcategory.value = selectedSubcategoryId || "";
}

function renderSubcategoryCategorySelector(selectedCategoryId = "") {
  const activeCategories = categories
    .filter((category) => category.is_active !== false)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  subcategoryFields.category.innerHTML =
    '<option value="">Selecciona una categoría</option>' +
    activeCategories
      .map((category) => `<option value="${escapeHTML(category.id)}">${escapeHTML(category.name)}</option>`)
      .join("");

  subcategoryFields.category.value = selectedCategoryId || "";
}

function resetForm() {
  form.reset();
  fields.id.value = "";
  fields.image.value = "";
  fields.stockQuantity.value = "";
  fields.lowStock.value = "";
  selectedProductFile = null;
  productFileInput.value = "";
  imagePreview.src = DEFAULT_IMAGE;
  setUploadStatus("Selecciona una imagen. Se subirá al guardar el producto.");
  formTitle.textContent = "Agregar nuevo producto";
  saveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Guardar producto';
  renderProductSelectors();
}

function resetBrandForm() {
  brandForm.reset();
  brandFields.id.value = "";
  brandFields.sort.value = 0;
  brandFields.active.value = "true";
  selectedBrandFile = null;
  brandFileInput.value = "";
  setBrandUploadStatus("Selecciona un logo. Se subirá al guardar la marca.");
  brandFormTitle.textContent = "Agregar nueva marca";
  brandSaveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Guardar marca';
}

function resetCategoryForm() {
  categoryForm.reset();
  categoryFields.id.value = "";
  categoryFields.sort.value = 0;
  categoryFields.active.value = "true";
  categoryFormTitle.textContent = "Agregar nueva categoría";
  categorySaveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Guardar categoría';
}

function resetSubcategoryForm() {
  subcategoryForm.reset();
  subcategoryFields.id.value = "";
  subcategoryFields.sort.value = 0;
  subcategoryFields.active.value = "true";
  subcategoryFormTitle.textContent = "Agregar nueva subcategoría";
  subcategorySaveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Guardar subcategoría';
  renderSubcategoryCategorySelector();
}

async function uploadProductImage(file) {
  if (!file) return fields.image.value.trim() || DEFAULT_IMAGE;

  const validationError = validateImageFile(file, MAX_PRODUCT_IMAGE_SIZE, "producto");
  if (validationError) {
    throw new Error(validationError);
  }

  const extension = file.name.split(".").pop()?.toLowerCase() || "jpg";
  const cleanName = file.name
    .replace(/\.[^/.]+$/, "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");

  const filePath = `products/${Date.now()}-${cleanName || "producto"}.${extension}`;

  setUploadStatus("Subiendo imagen a Supabase Storage...");

  const { error: uploadError } = await window.nymSupabase.storage.from(PRODUCT_IMAGES_BUCKET).upload(filePath, file, {
    cacheControl: "3600",
    upsert: false,
  });

  if (uploadError) throw uploadError;

  const { data } = window.nymSupabase.storage.from(PRODUCT_IMAGES_BUCKET).getPublicUrl(filePath);

  if (!data?.publicUrl) {
    throw new Error("No se pudo obtener la URL pública de la imagen.");
  }

  setUploadStatus("Imagen subida correctamente.", "success");
  return data.publicUrl;
}

// ---- admin-brands.js ----
async function uploadBrandLogo(file) {
  if (!file) return brandFields.logo.value.trim();

  const validationError = validateImageFile(file, MAX_BRAND_LOGO_SIZE, "logo");
  if (validationError) {
    throw new Error(validationError);
  }

  const extension = file.name.split(".").pop()?.toLowerCase() || "jpg";
  const cleanName = file.name
    .replace(/\.[^/.]+$/, "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");

  const filePath = `logos/${Date.now()}-${cleanName || "marca"}.${extension}`;

  setBrandUploadStatus("Subiendo logo a Supabase Storage...");

  const { error: uploadError } = await window.nymSupabase.storage.from(BRAND_LOGOS_BUCKET).upload(filePath, file, {
    cacheControl: "3600",
    upsert: false,
  });

  if (uploadError) throw uploadError;

  const { data } = window.nymSupabase.storage.from(BRAND_LOGOS_BUCKET).getPublicUrl(filePath);

  if (!data?.publicUrl) {
    throw new Error("No se pudo obtener la URL pública del logo.");
  }

  setBrandUploadStatus("Logo subido correctamente.", "success");
  return data.publicUrl;
}

function renderBrandsList() {
  brandsList.innerHTML = brands.length
    ? brands
        .map(
          (brand) => `
        <div class="simple-item">
          <span>
            ${escapeHTML(brand.name || "Marca sin nombre")}
            ${brand.is_active === false ? '<span class="admin-tag stock-tag unavailable">Inactivo</span>' : ""}
          </span>

          <div class="brand-actions">
            <button class="icon-action" type="button" data-brand-edit="${escapeHTML(brand.id)}" title="Editar marca">
              <i class="fa-solid fa-pen"></i>
            </button>

            <button class="icon-action danger" type="button" data-brand-delete="${escapeHTML(brand.id)}" title="Eliminar marca">
              <i class="fa-solid fa-trash"></i>
            </button>
          </div>
        </div>
      `,
        )
        .join("")
    : `
      <div class="empty-state-admin">
        <i class="fa-solid fa-tags"></i>
        <h3>No hay marcas registradas</h3>
        <p>Agrega tu primera marca desde el formulario.</p>
      </div>
    `;
}

// ---- admin-taxonomy.js ----
function renderCategoriesList() {
  categoriesList.innerHTML = categories.length
    ? categories
        .map(
          (category) => `
        <div class="simple-item">
          <span>
            ${escapeHTML(category.name || "Categoría sin nombre")}
            ${category.is_active === false ? '<span class="admin-tag stock-tag unavailable">Inactivo</span>' : ""}
          </span>

          <div class="brand-actions">
            <button class="icon-action" type="button" data-category-edit="${escapeHTML(category.id)}" title="Editar categoría">
              <i class="fa-solid fa-pen"></i>
            </button>

            <button class="icon-action danger" type="button" data-category-delete="${escapeHTML(category.id)}" title="Eliminar categoría">
              <i class="fa-solid fa-trash"></i>
            </button>
          </div>
        </div>
      `,
        )
        .join("")
    : `
      <div class="empty-state-admin">
        <i class="fa-solid fa-layer-group"></i>
        <h3>No hay categorías registradas</h3>
        <p>Agrega tu primera categoría desde el formulario.</p>
      </div>
    `;
}

function renderSubcategoriesList() {
  subcategoriesList.innerHTML = subcategories.length
    ? subcategories
        .map((subcategory) => {
          const parentCategory = categories.find((category) => category.id === subcategory.category_id);

          return `
          <div class="simple-item">
            <span>
              ${escapeHTML(subcategory.name || "Subcategoría sin nombre")}
              <small>Categoría: ${escapeHTML(parentCategory?.name || "Sin categoría")}</small>
              ${subcategory.is_active === false ? '<span class="admin-tag stock-tag unavailable">Inactivo</span>' : ""}
            </span>

            <div class="brand-actions">
              <button class="icon-action" type="button" data-subcategory-edit="${escapeHTML(subcategory.id)}" title="Editar subcategoría">
                <i class="fa-solid fa-pen"></i>
              </button>

              <button class="icon-action danger" type="button" data-subcategory-delete="${escapeHTML(subcategory.id)}" title="Eliminar subcategoría">
                <i class="fa-solid fa-trash"></i>
              </button>
            </div>
          </div>
        `;
        })
        .join("")
    : `
      <div class="empty-state-admin">
        <i class="fa-solid fa-sitemap"></i>
        <h3>No hay subcategorías registradas</h3>
        <p>Agrega tu primera subcategoría desde el formulario.</p>
      </div>
    `;
}

// ---- admin-products-data.js ----
function renderProducts() {
  const query = search.value.trim().toLowerCase();
  const selectedBrand = brandFilter.value;
  const selectedCategory = categoryFilter.value;
  const selectedSubcategory = subcategoryFilter.value;
  const selectedStock = stockFilter.value;

  const filtered = products.filter((product) => {
    const text = `
      ${product.name || ""}
      ${product.brand || ""}
      ${product.category || ""}
      ${product.subcategory || ""}
      ${product.stock_status || ""}
      ${product.description || ""}
    `.toLowerCase();

    return (
      product.is_active !== false &&
      (query === "" || text.includes(query)) &&
      (selectedBrand === "all" || product.brand_id === selectedBrand) &&
      (selectedCategory === "all" || product.category_id === selectedCategory) &&
      (selectedSubcategory === "all" || product.subcategory_id === selectedSubcategory) &&
      (selectedStock === "all" || product.stock_status === selectedStock)
    );
  });

  const sorted = [...filtered].sort(sortAdminProducts);
  const totalPages = Math.max(1, Math.ceil(sorted.length / adminProductPageSize));

  if (adminProductPage > totalPages) {
    adminProductPage = totalPages;
  }

  const start = (adminProductPage - 1) * adminProductPageSize;
  const pageProducts = sorted.slice(start, start + adminProductPageSize);

  list.innerHTML = sorted.length
    ? renderAdminProductTable(pageProducts)
    : renderAdminEmptyState({
        title: "No hay productos para mostrar",
        message: "Agrega un producto o cambia los filtros.",
      });

  renderProductPagination(sorted.length, start, pageProducts.length, totalPages);
  renderStockList();
  renderBrandsList();
  renderCategoriesList();
  renderSubcategoriesList();
  updateStats();
}

function sortAdminProducts(a, b) {
  const [field, direction] = adminProductSort.split("_");
  const multiplier = direction === "desc" ? -1 : 1;

  if (field === "stock") {
    const stockA = Number.isFinite(Number(a.stock_quantity)) ? Number(a.stock_quantity) : Number.MAX_SAFE_INTEGER;
    const stockB = Number.isFinite(Number(b.stock_quantity)) ? Number(b.stock_quantity) : Number.MAX_SAFE_INTEGER;
    if (stockA !== stockB) return (stockA - stockB) * multiplier;
    return String(a.stock_status || "").localeCompare(String(b.stock_status || "")) * multiplier;
  }

  if (field === "created") {
    const dateA = new Date(a.created_at || 0).getTime();
    const dateB = new Date(b.created_at || 0).getTime();
    return (dateA - dateB) * multiplier;
  }

  const valueA = String(a[field] || "").toLowerCase();
  const valueB = String(b[field] || "").toLowerCase();
  return valueA.localeCompare(valueB) * multiplier;
}

function renderProductPagination(totalProducts, start, shownProducts, totalPages) {
  if (!productPagination) return;
  productPagination.innerHTML = renderAdminProductPagination({ totalProducts, start, shownProducts, totalPages });
}

function resetAdminProductPage() {
  adminProductPage = 1;
  renderProducts();
}

function renderStockList() {
  const activeProducts = products.filter((product) => product.is_active !== false).sort(sortAdminProducts);
  renderStockMovementProductOptions();

  stockList.innerHTML = activeProducts.length
    ? activeProducts
        .map(
          (product) => `
        <div class="simple-item">
          <span>
            ${escapeHTML(product.name || "Producto sin nombre")}
            <small>
              ${escapeHTML(product.brand || "Sin marca")} /
              ${escapeHTML(product.category || "Sin categoría")}
              ${product.subcategory ? " / " + escapeHTML(product.subcategory) : ""}
            </small>
          </span>

          <span class="table-meta">
            <span class="admin-tag stock-tag ${getStockClass(product.stock_status)}">
              ${escapeHTML(product.stock_status || "Disponible")}
            </span>
            <small>
              ${
                Number.isFinite(Number(product.stock_quantity))
                  ? `${Number(product.stock_quantity)} unidades`
                  : "Sin cantidad"
              }
            </small>
          </span>
        </div>
      `,
        )
        .join("")
    : `
      <div class="empty-state-admin">
        <i class="fa-solid fa-box-open"></i>
        <h3>No hay productos</h3>
        <p>Cuando agregues productos, aquí verás su stock.</p>
      </div>
    `;
}

// ---- admin-brands-data.js ----
async function loadBrands() {
  const { data, error } = await window.nymSupabase
    .from("brands")
    .select("*")
    .order("sort_order", { ascending: true })
    .order("name", { ascending: true });

  if (error) throw error;

  brands = data || [];
  renderBrandsList();
  renderProductSelectors(fields.brand.value, fields.category.value, fields.subcategory.value);
  updateStats();
}

// ---- admin-taxonomy-data.js ----
async function loadCategories() {
  const { data, error } = await window.nymSupabase
    .from("categories")
    .select("*")
    .order("sort_order", { ascending: true })
    .order("name", { ascending: true });

  if (error) throw error;

  categories = data || [];
  renderCategoriesList();
  renderSubcategoryCategorySelector(subcategoryFields.category.value);
  renderProductSelectors(fields.brand.value, fields.category.value, fields.subcategory.value);
  updateStats();
}

async function loadSubcategories() {
  const { data, error } = await window.nymSupabase
    .from("subcategories")
    .select("*")
    .order("sort_order", { ascending: true })
    .order("name", { ascending: true });

  if (error) throw error;

  subcategories = data || [];
  renderSubcategoriesList();
  renderSubcategoryCategorySelector(subcategoryFields.category.value);
  renderSubcategoryProductSelector(fields.category.value, fields.subcategory.value);
  updateStats();
}

// ---- admin-products-save.js ----
async function loadProducts() {
  const pageSize = 1000;
  const rows = [];

  for (let from = 0; ; from += pageSize) {
    const to = from + pageSize - 1;
    const { data, error } = await window.nymSupabase
      .from("products")
      .select("*")
      .order("sort_order", { ascending: true })
      .order("created_at", { ascending: false })
      .range(from, to);

    if (error) throw error;

    rows.push(...(data || []));
    if (!data || data.length < pageSize) break;
  }

  products = rows;
  renderProductFilters();
  renderProducts();
}

async function saveProduct(payload, id) {
  const legacyPayload = { ...payload };
  delete legacyPayload.stock_quantity;
  delete legacyPayload.low_stock_threshold;

  if (id) {
    let { error } = await window.nymSupabase.from("products").update(payload).eq("id", id);

    if (error && /stock_quantity|low_stock_threshold|column/i.test(error.message || "")) {
      const retry = await window.nymSupabase.from("products").update(legacyPayload).eq("id", id);
      error = retry.error;

      if (!error) {
        showNotice(notice, "Producto actualizado. Para guardar cantidades, aplica la migracion de stock.", "warning");
        return;
      }
    }

    if (error) throw error;

    showNotice(notice, "Producto actualizado correctamente.");
  } else {
    let { error } = await window.nymSupabase.from("products").insert([payload]);

    if (error && /stock_quantity|low_stock_threshold|column/i.test(error.message || "")) {
      const retry = await window.nymSupabase.from("products").insert([legacyPayload]);
      error = retry.error;

      if (!error) {
        showNotice(notice, "Producto agregado. Para guardar cantidades, aplica la migracion de stock.", "warning");
        return;
      }
    }

    if (error) throw error;

    showNotice(notice, "Producto agregado correctamente.");
  }
}

// ---- admin-brands-save.js ----
async function saveBrand(payload, id) {
  if (id) {
    const { error } = await window.nymSupabase.from("brands").update(payload).eq("id", id);

    if (error) throw error;

    showNotice(brandNotice, "Marca actualizada correctamente.");
  } else {
    const { error } = await window.nymSupabase.from("brands").insert([payload]);

    if (error) throw error;

    showNotice(brandNotice, "Marca agregada correctamente.");
  }
}

// ---- admin-taxonomy-save.js ----
async function saveCategory(payload, id) {
  if (id) {
    const { error } = await window.nymSupabase.from("categories").update(payload).eq("id", id);

    if (error) throw error;

    showNotice(categoryNotice, "Categoría actualizada correctamente.");
  } else {
    const { error } = await window.nymSupabase.from("categories").insert([payload]);

    if (error) throw error;

    showNotice(categoryNotice, "Categoría agregada correctamente.");
  }
}

async function saveSubcategory(payload, id) {
  if (id) {
    const { error } = await window.nymSupabase.from("subcategories").update(payload).eq("id", id);

    if (error) throw error;

    showNotice(subcategoryNotice, "Subcategoría actualizada correctamente.");
  } else {
    const { error } = await window.nymSupabase.from("subcategories").insert([payload]);

    if (error) throw error;

    showNotice(subcategoryNotice, "Subcategoría agregada correctamente.");
  }
}

// ---- admin-products-delete.js ----
async function deleteProduct(id) {
  const { error } = await window.nymSupabase.from("products").delete().eq("id", id);

  if (error) throw error;
}

// ---- admin-brands-delete.js ----
async function deleteBrand(id) {
  const inUse = products.some((product) => product.brand_id === id);

  if (inUse) {
    throw new Error("No puedes eliminar esta marca porque está asignada a uno o más productos.");
  }

  const { error } = await window.nymSupabase.from("brands").delete().eq("id", id);

  if (error) throw error;
}

// ---- admin-taxonomy-delete.js ----
async function deleteCategory(id) {
  const categoryHasProducts = products.some((product) => product.category_id === id);
  const categoryHasSubcategories = subcategories.some((subcategory) => subcategory.category_id === id);

  if (categoryHasProducts || categoryHasSubcategories) {
    throw new Error("No puedes eliminar esta categoría porque tiene productos o subcategorías relacionadas.");
  }

  const { error } = await window.nymSupabase.from("categories").delete().eq("id", id);

  if (error) throw error;
}

async function deleteSubcategory(id) {
  const inUse = products.some((product) => product.subcategory_id === id);

  if (inUse) {
    throw new Error("No puedes eliminar esta subcategoría porque está asignada a uno o más productos.");
  }

  const { error } = await window.nymSupabase.from("subcategories").delete().eq("id", id);

  if (error) throw error;
}

// ---- admin-company.js ----
function updateCompanyPreview() {
  companyPreview.phone.textContent = companyFields.phone.value || "-";
  companyPreview.email.textContent = companyFields.email.value || "-";
  companyPreview.address.textContent = companyFields.address.value || "-";
  companyPreview.hours.textContent = companyFields.hours.value || "-";
}

async function loadCompanySettings() {
  const { data, error } = await window.nymSupabase.from("company_settings").select("*").limit(1).maybeSingle();

  if (error) throw error;

  if (!data) {
    companyFields.id.value = "";
    companyFields.phone.value = "966 441 035";
    companyFields.phoneRaw.value = "51966441035";
    companyFields.email.value = "oliveravelasquezluis@gmail.com";
    companyFields.address.value = "Av. Republica de Argentina 211, Lima 15079";
    companyFields.hours.value = "Lun - Sáb / 10:00 am - 5:00 pm";
    companyFields.whatsappUrl.value = "https://wa.me/51966441035";
    companyFields.mapUrl.value = "https://www.google.com/maps/place/Av.+Republica+de+Argentina+211,+Lima+15079/";
    companyFields.mapEmbed.value = "";
    updateCompanyPreview();
    return;
  }

  companyFields.id.value = data.id || "";
  companyFields.phone.value = data.phone || "";
  companyFields.phoneRaw.value = data.phone_raw || "";
  companyFields.email.value = data.email || "";
  companyFields.address.value = data.address || "";
  companyFields.hours.value = data.hours || "";
  companyFields.whatsappUrl.value = data.whatsapp_url || "";
  companyFields.mapUrl.value = data.map_url || "";
  companyFields.mapEmbed.value = data.map_embed || "";
  updateCompanyPreview();
}

async function saveCompanySettings() {
  const payload = {
    phone: companyFields.phone.value.trim(),
    phone_raw: companyFields.phoneRaw.value.trim(),
    email: companyFields.email.value.trim(),
    address: companyFields.address.value.trim(),
    hours: companyFields.hours.value.trim(),
    whatsapp_url: companyFields.whatsappUrl.value.trim(),
    map_url: companyFields.mapUrl.value.trim(),
    map_embed: companyFields.mapEmbed.value.trim(),
  };

  if (!payload.phone || !payload.email || !payload.address) {
    showNotice(companyNotice, "Completa teléfono, correo y dirección.", "error");
    return;
  }

  companySaveBtn.disabled = true;

  try {
    if (companyFields.id.value) {
      const { error } = await window.nymSupabase
        .from("company_settings")
        .update(payload)
        .eq("id", companyFields.id.value);

      if (error) throw error;
    } else {
      const { data, error } = await window.nymSupabase.from("company_settings").insert([payload]).select().single();

      if (error) throw error;

      companyFields.id.value = data.id;
    }

    updateCompanyPreview();
    showNotice(companyNotice, "Datos de empresa guardados correctamente.");
  } catch (error) {
    console.error(error);
    showNotice(companyNotice, error.message || "No se pudieron guardar los datos.", "error");
  } finally {
    companySaveBtn.disabled = false;
  }
}

// ---- admin-leads.js ----
const leadStatusLabels = {
  nuevo: "Nuevo",
  atendido: "Atendido",
  descartado: "Archivado",
};

function formatLeadDate(value) {
  if (!value) return "Sin fecha";

  try {
    return new Intl.DateTimeFormat("es-PE", {
      dateStyle: "medium",
      timeStyle: "short",
    }).format(new Date(value));
  } catch {
    return "Sin fecha";
  }
}

function getLeadStatusClass(status) {
  if (status === "atendido") return "available";
  if (status === "descartado") return "unavailable";
  return "preorder";
}

function getLeadSearchText(lead) {
  return [lead.nombre, lead.empresa, lead.correo, lead.telefono, lead.tipo, lead.categoria, lead.estado, lead.mensaje]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
}

function buildLeadWhatsappUrl(lead) {
  const phone = String(lead.telefono || "").replace(/\D/g, "");
  if (!phone) return "";

  const normalizedPhone = phone.length === 9 ? `51${phone}` : phone;
  const message = [
    `Hola ${lead.nombre || ""}`.trim(),
    "Te escribimos de INDUSTRIAL IMPORT COMPANY S.R.L. para atender tu consulta.",
  ].join("\n");

  return `https://wa.me/${normalizedPhone}?text=${encodeURIComponent(message)}`;
}

function getFilteredLeads() {
  const query = (leadSearch?.value || "").trim().toLowerCase();
  const status = leadStatusFilter?.value || "all";

  return contactLeads.filter((lead) => {
    const matchesSearch = !query || getLeadSearchText(lead).includes(query);
    const matchesStatus = status === "all" || (lead.estado || "nuevo") === status;
    return matchesSearch && matchesStatus;
  });
}

function renderLeads() {
  if (!leadsList) return;

  const leads = getFilteredLeads();

  leadsList.innerHTML = leads.length
    ? leads
        .map((lead) => {
          const status = lead.estado || "nuevo";
          const whatsappUrl = buildLeadWhatsappUrl(lead);

          return `
          <div class="simple-item lead-item">
            <span class="lead-item-main">
              ${escapeHTML(lead.nombre || "Contacto sin nombre")}
              <small>
                ${escapeHTML(lead.empresa || "Sin empresa")} /
                ${escapeHTML(lead.correo || "Sin correo")} /
                ${escapeHTML(lead.telefono || "Sin telefono")}
              </small>
              <small>
                ${escapeHTML(lead.tipo || "Consulta")} - ${escapeHTML(lead.categoria || "Sin categoria")}
              </small>
              <small class="lead-message">${escapeHTML(lead.mensaje || "Sin mensaje")}</small>
              <label class="lead-notes">
                <small>Notas internas</small>
                <textarea data-lead-notes="${escapeHTML(lead.id)}" placeholder="Ej: llamar por la tarde, pidio ABB...">${escapeHTML(lead.admin_notes || "")}</textarea>
              </label>
              <small>${escapeHTML(formatLeadDate(lead.created_at))}</small>
            </span>

            <span class="lead-actions">
              <span class="admin-tag stock-tag ${getLeadStatusClass(status)}">${escapeHTML(leadStatusLabels[status] || status)}</span>
              ${whatsappUrl ? `<a class="admin-btn admin-btn-light" href="${escapeHTML(whatsappUrl)}" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a>` : ""}
              <button class="admin-btn admin-btn-light" type="button" data-lead-save-notes="${escapeHTML(lead.id)}">Guardar nota</button>
              ${status !== "atendido" ? `<button class="admin-btn admin-btn-primary" type="button" data-lead-status="atendido" data-lead-id="${escapeHTML(lead.id)}">Atendido</button>` : ""}
              ${status !== "descartado" ? `<button class="admin-btn admin-btn-light" type="button" data-lead-status="descartado" data-lead-id="${escapeHTML(lead.id)}">Archivar</button>` : ""}
              ${status !== "nuevo" ? `<button class="admin-btn admin-btn-light" type="button" data-lead-status="nuevo" data-lead-id="${escapeHTML(lead.id)}">Reabrir</button>` : ""}
            </span>
          </div>
        `;
        })
        .join("")
    : `
      <div class="empty-state-admin">
        <i class="fa-solid fa-inbox"></i>
        <h3>No hay leads para este filtro</h3>
        <p>Las consultas nuevas y cotizaciones guardadas apareceran aqui.</p>
      </div>
    `;

  leadsList.querySelectorAll("[data-lead-status]").forEach((button) => {
    button.addEventListener("click", () => {
      saveLeadStatus(button.dataset.leadId, button.dataset.leadStatus);
    });
  });

  leadsList.querySelectorAll("[data-lead-save-notes]").forEach((button) => {
    button.addEventListener("click", () => {
      const textarea = leadsList.querySelector(`[data-lead-notes="${CSS.escape(button.dataset.leadSaveNotes)}"]`);
      saveLeadNotes(button.dataset.leadSaveNotes, textarea?.value || "");
    });
  });
}

async function saveLeadStatus(leadId, status) {
  if (!leadId || !status) return;

  try {
    const { error } = await window.nymSupabase.from("contact_leads").update({ estado: status }).eq("id", leadId);

    if (error) throw error;

    contactLeads = contactLeads.map((lead) =>
      String(lead.id) === String(leadId) ? { ...lead, estado: status } : lead,
    );

    renderLeads();
    if (leadsNotice) showNotice(leadsNotice, "Lead actualizado correctamente.");
  } catch (error) {
    console.error(error);
    if (leadsNotice) showNotice(leadsNotice, error.message || "No se pudo actualizar el lead.", "error");
  }
}

async function saveLeadNotes(leadId, notes) {
  if (!leadId) return;

  try {
    const { error } = await window.nymSupabase
      .from("contact_leads")
      .update({ admin_notes: notes.trim() })
      .eq("id", leadId);

    if (error) throw error;

    contactLeads = contactLeads.map((lead) =>
      String(lead.id) === String(leadId) ? { ...lead, admin_notes: notes.trim() } : lead,
    );

    if (leadsNotice) showNotice(leadsNotice, "Nota guardada correctamente.");
  } catch (error) {
    console.error(error);
    if (leadsNotice) {
      showNotice(
        leadsNotice,
        "No se pudo guardar la nota. Aplica la migracion de leads si falta la columna.",
        "warning",
      );
    }
  }
}

async function loadContactLeads() {
  if (!leadsList) return;

  try {
    const { data, error } = await window.nymSupabase
      .from("contact_leads")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(100);

    if (error) throw error;

    contactLeads = data || [];
    renderLeads();
  } catch (error) {
    console.error(error);
    leadsList.innerHTML = `
      <div class="empty-state-admin">
        <i class="fa-solid fa-triangle-exclamation"></i>
        <h3>No se pudieron cargar los leads</h3>
        <p>${escapeHTML(error.message || "Revisa las politicas RLS de contact_leads.")}</p>
      </div>
    `;
  }
}

leadSearch?.addEventListener("input", renderLeads);
leadStatusFilter?.addEventListener("change", renderLeads);

// ---- admin-stock.js ----
function getProductCurrentQuantity(product) {
  return Number.isFinite(Number(product?.stock_quantity)) ? Number(product.stock_quantity) : 0;
}

function getStockMovementLabel(type) {
  const labels = {
    entrada: "Entrada",
    salida: "Salida",
    ajuste: "Ajuste",
  };

  return labels[type] || type || "Movimiento";
}

function getStockMovementClass(type) {
  if (type === "salida") return "unavailable";
  if (type === "ajuste") return "preorder";
  return "available";
}

function formatStockMovementDate(value) {
  if (!value) return "Sin fecha";

  return new Intl.DateTimeFormat("es-PE", {
    dateStyle: "short",
    timeStyle: "short",
  }).format(new Date(value));
}

function renderStockMovementProductOptions() {
  if (!stockMovementProduct) return;

  const activeProducts = products.filter((product) => product.is_active !== false).sort(sortAdminProducts);

  stockMovementProduct.innerHTML = [
    '<option value="">Selecciona un producto</option>',
    ...activeProducts.map((product) => {
      const quantity = getProductCurrentQuantity(product);
      const brand = product.brand ? ` / ${product.brand}` : "";
      return `<option value="${escapeHTML(product.id)}">${escapeHTML(product.name || "Producto sin nombre")}${escapeHTML(brand)} (${quantity} und.)</option>`;
    }),
  ].join("");
}

function renderStockMovements() {
  if (!stockMovementList) return;

  stockMovementList.innerHTML = stockMovements.length
    ? stockMovements
        .slice(0, 40)
        .map((movement) => {
          const productName = movement.products?.name || "Producto eliminado";
          const productBrand = movement.products?.brand ? ` / ${movement.products.brand}` : "";
          const delta = Number(movement.quantity_delta || 0);
          const deltaLabel = delta > 0 ? `+${delta}` : String(delta);

          return `
            <div class="simple-item stock-history-item">
              <span>
                ${escapeHTML(productName)}
                <small>
                  ${escapeHTML(productBrand.replace(/^ \/ /, ""))}
                  ${movement.note ? " / " + escapeHTML(movement.note) : ""}
                </small>
              </span>

              <span class="table-meta">
                <span class="admin-tag stock-tag ${getStockMovementClass(movement.movement_type)}">
                  ${escapeHTML(getStockMovementLabel(movement.movement_type))}
                </span>
                <small>${escapeHTML(deltaLabel)} und. / nuevo: ${escapeHTML(movement.new_quantity)}</small>
                <small>${escapeHTML(formatStockMovementDate(movement.created_at))}</small>
              </span>
            </div>
          `;
        })
        .join("")
    : `
      <div class="empty-state-admin">
        <i class="fa-solid fa-clock-rotate-left"></i>
        <h3>Sin movimientos registrados</h3>
        <p>Cuando registres entradas, salidas o ajustes, aparecerán aquí.</p>
      </div>
    `;
}

async function loadStockMovements() {
  if (!stockMovementList) return;

  const { data, error } = await window.nymSupabase
    .from("stock_movements")
    .select("*, products(name, brand)")
    .order("created_at", { ascending: false })
    .limit(80);

  if (error) {
    stockMovementList.innerHTML = `
      <div class="empty-state-admin">
        <i class="fa-solid fa-database"></i>
        <h3>No se pudo cargar el historial</h3>
        <p>${escapeHTML(error.message || "Aplica la migración de movimientos de stock.")}</p>
      </div>
    `;
    return;
  }

  stockMovements = data || [];
  renderStockMovements();
}

function calculateStockMovement(product, type, quantity) {
  const previousQuantity = getProductCurrentQuantity(product);
  let newQuantity = previousQuantity;

  if (type === "entrada") newQuantity += quantity;
  if (type === "salida") newQuantity -= quantity;
  if (type === "ajuste") newQuantity = quantity;

  if (newQuantity < 0) {
    throw new Error("La salida no puede dejar el stock en negativo.");
  }

  return {
    previousQuantity,
    newQuantity,
    quantityDelta: newQuantity - previousQuantity,
  };
}

async function saveStockMovement(event) {
  event.preventDefault();

  const product = products.find((item) => String(item.id) === String(stockMovementProduct.value));
  const type = stockMovementType.value;
  const quantity = Number(stockMovementQuantity.value);

  if (!product || !type || !Number.isInteger(quantity) || quantity < 0) {
    showNotice(stockMovementNotice, "Selecciona producto, tipo y una cantidad válida.", "error");
    return;
  }

  if (quantity === 0 && type !== "ajuste") {
    showNotice(stockMovementNotice, "Entradas y salidas deben ser mayores a cero.", "error");
    return;
  }

  try {
    const movement = calculateStockMovement(product, type, quantity);
    const nextStockStatus =
      movement.newQuantity <= 0
        ? "Sin stock"
        : String(product.stock_status || "")
              .toLowerCase()
              .includes("sin")
          ? "Disponible"
          : product.stock_status || "Disponible";

    const { error: productError } = await window.nymSupabase
      .from("products")
      .update({
        stock_quantity: movement.newQuantity,
        stock_status: nextStockStatus,
      })
      .eq("id", product.id);

    if (productError) throw productError;

    const { error: movementError } = await window.nymSupabase.from("stock_movements").insert([
      {
        product_id: product.id,
        movement_type: type,
        quantity_delta: movement.quantityDelta,
        previous_quantity: movement.previousQuantity,
        new_quantity: movement.newQuantity,
        note: stockMovementNote.value.trim() || null,
        user_id: currentUser?.id || null,
        user_email: currentUser?.email || null,
      },
    ]);

    if (movementError) throw movementError;

    stockMovementForm.reset();
    showNotice(stockMovementNotice, "Movimiento de stock registrado correctamente.");
    await loadProducts();
    await loadStockMovements();
  } catch (error) {
    console.error(error);
    showNotice(stockMovementNotice, error.message || "No se pudo registrar el movimiento.", "error");
  }
}

stockMovementForm?.addEventListener("submit", saveStockMovement);

// ---- admin-session.js ----
async function requireSession() {
  const { data, error } = await window.nymSupabase.auth.getSession();

  if (error || !data.session) {
    window.location.href = "admin-login.html";
    return false;
  }

  currentUser = data.session.user;
  localStorage.setItem("nymAdminSession", "active");
  localStorage.setItem("nymAdminUser", currentUser.email || "admin");
  return true;
}

// ---- admin-events-core.js ----
menuButtons.forEach((button) => {
  button.addEventListener("click", () => openSection(button.dataset.section));
});

// ---- admin-events-products.js ----
productFileInput.addEventListener("change", () => {
  const file = productFileInput.files?.[0];

  if (!file) {
    selectedProductFile = null;
    setUploadStatus("Selecciona una imagen. Se subirá al guardar el producto.");
    return;
  }

  const validationError = validateImageFile(file, MAX_PRODUCT_IMAGE_SIZE, "producto");
  if (validationError) {
    selectedProductFile = null;
    productFileInput.value = "";
    setUploadStatus(validationError, "error");
    return;
  }

  selectedProductFile = file;
  imagePreview.src = URL.createObjectURL(file);
  setUploadStatus(`Imagen lista: ${file.name} (${formatFileSize(file.size)})`);
});

brandFileInput.addEventListener("change", () => {
  const file = brandFileInput.files?.[0];

  if (!file) {
    selectedBrandFile = null;
    setBrandUploadStatus("Selecciona un logo. Se subirá al guardar la marca.");
    return;
  }

  const validationError = validateImageFile(file, MAX_BRAND_LOGO_SIZE, "logo");
  if (validationError) {
    selectedBrandFile = null;
    brandFileInput.value = "";
    setBrandUploadStatus(validationError, "error");
    return;
  }

  selectedBrandFile = file;
  setBrandUploadStatus(`Logo listo: ${file.name} (${formatFileSize(file.size)})`);
});

fields.category.addEventListener("change", () => {
  renderSubcategoryProductSelector(fields.category.value);
});

// Al elegir subcategoría → auto-selecciona su categoría padre
fields.subcategory.addEventListener("change", () => {
  const subId = fields.subcategory.value;
  if (!subId) return;

  const sub = subcategories.find((s) => s.id === subId);
  if (!sub || !sub.category_id) return;

  // Si la categoría padre es distinta a la actual, actualizarla
  if (fields.category.value !== sub.category_id) {
    fields.category.value = sub.category_id;
    // Refrescar lista de subcategorías para mostrar solo las de esa categoría
    // manteniendo la subcategoría que el usuario ya eligió
    renderSubcategoryProductSelector(sub.category_id, subId);
  }
});

form.addEventListener("submit", async (event) => {
  event.preventDefault();

  const selectedBrand = brands.find((brand) => brand.id === fields.brand.value);
  const selectedCategory = categories.find((category) => category.id === fields.category.value);
  const selectedSubcategory = subcategories.find((subcategory) => subcategory.id === fields.subcategory.value);

  if (!fields.name.value.trim() || !selectedBrand || !selectedCategory) {
    showNotice(notice, "Completa nombre, marca y categoría.", "error");
    return;
  }

  saveBtn.disabled = true;

  try {
    const finalImageUrl = await uploadProductImage(selectedProductFile);

    const payload = {
      name: fields.name.value.trim(),
      brand_id: selectedBrand.id,
      category_id: selectedCategory.id,
      subcategory_id: selectedSubcategory?.id || null,
      brand: selectedBrand.name || "",
      category: selectedCategory.name || "",
      subcategory: selectedSubcategory?.name || "",
      image_url: finalImageUrl,
      stock_status: fields.stock.value,
      stock_quantity: fields.stockQuantity.value === "" ? null : Number(fields.stockQuantity.value),
      low_stock_threshold: fields.lowStock.value === "" ? null : Number(fields.lowStock.value),
      description: fields.desc.value.trim(),
      is_active: true,
    };

    await saveProduct(payload, fields.id.value);
    resetForm();
    await loadProducts();
  } catch (error) {
    console.error(error);
    setUploadStatus(error.message || "No se pudo subir la imagen.", "error");
    showNotice(notice, error.message || "No se pudo guardar el producto.", "error");
  } finally {
    saveBtn.disabled = false;
  }
});

list.addEventListener("click", async (event) => {
  const editButton = event.target.closest("[data-edit]");
  const deleteButton = event.target.closest("[data-delete]");

  if (editButton) {
    const product = products.find((item) => item.id === editButton.dataset.edit);
    if (!product) return;

    const brandId = product.brand_id || brands.find((brand) => brand.name === product.brand)?.id || "";
    const categoryId =
      product.category_id || categories.find((category) => category.name === product.category)?.id || "";
    const subcategoryId =
      product.subcategory_id || subcategories.find((subcategory) => subcategory.name === product.subcategory)?.id || "";

    fields.id.value = product.id;
    fields.name.value = product.name || "";
    fields.image.value = product.image_url || "";
    fields.stock.value = product.stock_status || "Disponible";
    fields.stockQuantity.value = Number.isFinite(Number(product.stock_quantity)) ? Number(product.stock_quantity) : "";
    fields.lowStock.value = Number.isFinite(Number(product.low_stock_threshold))
      ? Number(product.low_stock_threshold)
      : "";
    fields.desc.value = product.description || "";
    imagePreview.src = product.image_url || DEFAULT_IMAGE;

    selectedProductFile = null;
    productFileInput.value = "";

    setUploadStatus("Puedes mantener la imagen actual o seleccionar una nueva.");
    renderProductSelectors(brandId, categoryId, subcategoryId);

    formTitle.textContent = "Editar producto";
    saveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Actualizar producto';

    openSection("products");
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  if (deleteButton) {
    const product = products.find((item) => item.id === deleteButton.dataset.delete);

    const shouldDelete = await showAdminDialog({
      title: "Eliminar producto",
      message: `¿Seguro que deseas eliminar "${product?.name || "este producto"}"? Esta acción no se puede deshacer.`,
      confirmText: "Eliminar",
      danger: true,
    });

    if (!shouldDelete) return;

    try {
      await deleteProduct(deleteButton.dataset.delete);
      await loadProducts();
      showNotice(notice, "Producto eliminado correctamente.");
    } catch (error) {
      console.error(error);
      showNotice(notice, error.message || "No se pudo eliminar el producto.", "error");
    }
  }
});

productPagination?.addEventListener("click", (event) => {
  const button = event.target.closest("[data-product-page]");
  if (!button || button.disabled) return;

  adminProductPage += button.dataset.productPage === "next" ? 1 : -1;
  renderProducts();

  list.scrollIntoView({ behavior: "smooth", block: "start" });
});

productPagination?.addEventListener("change", (event) => {
  const select = event.target.closest("[data-product-page-size]");
  if (!select) return;

  adminProductPageSize = Number(select.value) || 25;
  resetAdminProductPage();
});

list.addEventListener("click", (event) => {
  const sortButton = event.target.closest("[data-product-sort]");
  if (!sortButton) return;

  adminProductSort = sortButton.dataset.productSort;
  if (productSort) productSort.value = adminProductSort;
  resetAdminProductPage();
});

// ---- admin-events-brands.js ----
brandForm.addEventListener("submit", async (event) => {
  event.preventDefault();

  if (!brandFields.name.value.trim()) {
    showNotice(brandNotice, "Completa el nombre de la marca.", "error");
    return;
  }

  brandSaveBtn.disabled = true;

  try {
    const uploadedLogoUrl = await uploadBrandLogo(selectedBrandFile);

    const payload = {
      name: brandFields.name.value.trim(),
      logo_url: uploadedLogoUrl,
      description: brandFields.description.value.trim(),
      sort_order: Number(brandFields.sort.value || 0),
      is_active: brandFields.active.value === "true",
    };

    await saveBrand(payload, brandFields.id.value);
    resetBrandForm();
    await loadBrands();
  } catch (error) {
    console.error(error);
    setBrandUploadStatus(error.message || "No se pudo subir el logo.", "error");
    showNotice(brandNotice, error.message || "No se pudo guardar la marca.", "error");
  } finally {
    brandSaveBtn.disabled = false;
  }
});

brandsList.addEventListener("click", async (event) => {
  const editButton = event.target.closest("[data-brand-edit]");
  const deleteButton = event.target.closest("[data-brand-delete]");

  if (editButton) {
    const brand = brands.find((item) => item.id === editButton.dataset.brandEdit);
    if (!brand) return;

    brandFields.id.value = brand.id;
    brandFields.name.value = brand.name || "";
    brandFields.logo.value = brand.logo_url || "";
    brandFields.description.value = brand.description || "";
    brandFields.sort.value = brand.sort_order || 0;
    brandFields.active.value = String(brand.is_active !== false);

    selectedBrandFile = null;
    brandFileInput.value = "";

    setBrandUploadStatus("Puedes mantener el logo actual o seleccionar uno nuevo.");
    brandFormTitle.textContent = "Editar marca";
    brandSaveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Actualizar marca';
  }

  if (deleteButton) {
    const brand = brands.find((item) => item.id === deleteButton.dataset.brandDelete);

    const shouldDelete = await showAdminDialog({
      title: "Eliminar marca",
      message: `¿Seguro que deseas eliminar "${brand?.name || "esta marca"}"?`,
      confirmText: "Eliminar",
      danger: true,
    });

    if (!shouldDelete) return;

    try {
      await deleteBrand(deleteButton.dataset.brandDelete);
      await loadBrands();
      showNotice(brandNotice, "Marca eliminada correctamente.");
    } catch (error) {
      console.error(error);
      showNotice(brandNotice, error.message || "No se pudo eliminar la marca.", "error");
    }
  }
});

// ---- admin-events-taxonomy.js ----
categoryForm.addEventListener("submit", async (event) => {
  event.preventDefault();

  const payload = {
    name: categoryFields.name.value.trim(),
    description: categoryFields.description.value.trim(),
    icon: categoryFields.icon.value.trim(),
    sort_order: Number(categoryFields.sort.value || 0),
    is_active: categoryFields.active.value === "true",
  };

  if (!payload.name) {
    showNotice(categoryNotice, "Completa el nombre de la categoría.", "error");
    return;
  }

  categorySaveBtn.disabled = true;

  try {
    await saveCategory(payload, categoryFields.id.value);
    resetCategoryForm();
    await loadCategories();
  } catch (error) {
    console.error(error);
    showNotice(categoryNotice, error.message || "No se pudo guardar la categoría.", "error");
  } finally {
    categorySaveBtn.disabled = false;
  }
});

categoriesList.addEventListener("click", async (event) => {
  const editButton = event.target.closest("[data-category-edit]");
  const deleteButton = event.target.closest("[data-category-delete]");

  if (editButton) {
    const category = categories.find((item) => item.id === editButton.dataset.categoryEdit);
    if (!category) return;

    categoryFields.id.value = category.id;
    categoryFields.name.value = category.name || "";
    categoryFields.description.value = category.description || "";
    categoryFields.icon.value = category.icon || "";
    categoryFields.sort.value = category.sort_order || 0;
    categoryFields.active.value = String(category.is_active !== false);

    categoryFormTitle.textContent = "Editar categoría";
    categorySaveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Actualizar categoría';
  }

  if (deleteButton) {
    const category = categories.find((item) => item.id === deleteButton.dataset.categoryDelete);

    const shouldDelete = await showAdminDialog({
      title: "Eliminar categoría",
      message: `¿Seguro que deseas eliminar "${category?.name || "esta categoría"}"?`,
      confirmText: "Eliminar",
      danger: true,
    });

    if (!shouldDelete) return;

    try {
      await deleteCategory(deleteButton.dataset.categoryDelete);
      await loadCategories();
      await loadSubcategories();
      showNotice(categoryNotice, "Categoría eliminada correctamente.");
    } catch (error) {
      console.error(error);
      showNotice(categoryNotice, error.message || "No se pudo eliminar la categoría.", "error");
    }
  }
});

subcategoryForm.addEventListener("submit", async (event) => {
  event.preventDefault();

  const selectedCategory = categories.find((category) => category.id === subcategoryFields.category.value);

  const payload = {
    name: subcategoryFields.name.value.trim(),
    category_id: selectedCategory?.id || null,
    description: subcategoryFields.description.value.trim(),
    sort_order: Number(subcategoryFields.sort.value || 0),
    is_active: subcategoryFields.active.value === "true",
  };

  if (!payload.name || !payload.category_id) {
    showNotice(subcategoryNotice, "Completa nombre y categoría principal.", "error");
    return;
  }

  subcategorySaveBtn.disabled = true;

  try {
    await saveSubcategory(payload, subcategoryFields.id.value);
    resetSubcategoryForm();
    await loadSubcategories();
  } catch (error) {
    console.error(error);
    showNotice(subcategoryNotice, error.message || "No se pudo guardar la subcategoría.", "error");
  } finally {
    subcategorySaveBtn.disabled = false;
  }
});

subcategoriesList.addEventListener("click", async (event) => {
  const editButton = event.target.closest("[data-subcategory-edit]");
  const deleteButton = event.target.closest("[data-subcategory-delete]");

  if (editButton) {
    const subcategory = subcategories.find((item) => item.id === editButton.dataset.subcategoryEdit);
    if (!subcategory) return;

    subcategoryFields.id.value = subcategory.id;
    subcategoryFields.name.value = subcategory.name || "";
    subcategoryFields.category.value = subcategory.category_id || "";
    subcategoryFields.description.value = subcategory.description || "";
    subcategoryFields.sort.value = subcategory.sort_order || 0;
    subcategoryFields.active.value = String(subcategory.is_active !== false);

    subcategoryFormTitle.textContent = "Editar subcategoría";
    subcategorySaveBtn.innerHTML = '<i class="fa-solid fa-floppy-disk"></i> Actualizar subcategoría';
  }

  if (deleteButton) {
    const subcategory = subcategories.find((item) => item.id === deleteButton.dataset.subcategoryDelete);

    const shouldDelete = await showAdminDialog({
      title: "Eliminar subcategoría",
      message: `¿Seguro que deseas eliminar "${subcategory?.name || "esta subcategoría"}"?`,
      confirmText: "Eliminar",
      danger: true,
    });

    if (!shouldDelete) return;

    try {
      await deleteSubcategory(deleteButton.dataset.subcategoryDelete);
      await loadSubcategories();
      showNotice(subcategoryNotice, "Subcategoría eliminada correctamente.");
    } catch (error) {
      console.error(error);
      showNotice(subcategoryNotice, error.message || "No se pudo eliminar la subcategoría.", "error");
    }
  }
});

// ---- admin-events-filters.js ----
fields.image.addEventListener("input", () => {
  if (!selectedProductFile) {
    imagePreview.src = fields.image.value.trim() || DEFAULT_IMAGE;
  }
});

imagePreview.addEventListener("error", () => {
  imagePreview.src = DEFAULT_IMAGE;
});

search.addEventListener("input", resetAdminProductPage);
brandFilter.addEventListener("change", resetAdminProductPage);
categoryFilter.addEventListener("change", () => {
  const selectedCategory = categoryFilter.value;

  const activeSubcategories = subcategories
    .filter((subcategory) => subcategory.is_active !== false)
    .filter((subcategory) => selectedCategory === "all" || subcategory.category_id === selectedCategory)
    .sort((a, b) => String(a.name || "").localeCompare(String(b.name || "")));

  subcategoryFilter.innerHTML =
    '<option value="all">Todas las subcategorías</option>' +
    activeSubcategories
      .map((subcategory) => `<option value="${escapeHTML(subcategory.id)}">${escapeHTML(subcategory.name)}</option>`)
      .join("");

  subcategoryFilter.value = "all";
  resetAdminProductPage();
});
subcategoryFilter.addEventListener("change", resetAdminProductPage);
stockFilter.addEventListener("change", resetAdminProductPage);
productSort?.addEventListener("change", () => {
  adminProductSort = productSort.value;
  resetAdminProductPage();
});

resetBtn.addEventListener("click", resetForm);
brandResetBtn.addEventListener("click", resetBrandForm);
categoryResetBtn.addEventListener("click", resetCategoryForm);
subcategoryResetBtn.addEventListener("click", resetSubcategoryForm);

// ---- admin-events-company.js ----
companyForm.addEventListener("submit", async (event) => {
  event.preventDefault();
  await saveCompanySettings();
});

companyReloadBtn.addEventListener("click", async () => {
  try {
    await loadCompanySettings();
    showNotice(companyNotice, "Datos recargados correctamente.");
  } catch (error) {
    console.error(error);
    showNotice(companyNotice, "No se pudieron recargar los datos.", "error");
  }
});

Object.values(companyFields).forEach((field) => {
  field.addEventListener("input", updateCompanyPreview);
});

// ---- admin-init.js ----
logoutBtn.addEventListener("click", async () => {
  await window.nymSupabase.auth.signOut();
  localStorage.removeItem("nymAdminSession");
  localStorage.removeItem("nymAdminUser");
  window.location.href = "admin-login.html";
});

(async function initAdmin() {
  try {
    const sessionOk = await requireSession();
    if (!sessionOk) return;

    await loadBrands();
    await loadCategories();
    await loadSubcategories();
    await loadProducts();
    await loadStockMovements();
    await loadCompanySettings();
    await loadContactLeads();
  } catch (error) {
    console.error(error);
    await showAdminAlert("No se pudo cargar el admin", error.message || String(error));
  }
})();
