const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const outFile = path.join(root, "js", "admin-app.js");
const adminModules = [
  "admin-core",
  "admin-components",
  "admin-products",
  "admin-brands",
  "admin-taxonomy",
  "admin-products-data",
  "admin-brands-data",
  "admin-taxonomy-data",
  "admin-products-save",
  "admin-brands-save",
  "admin-taxonomy-save",
  "admin-products-delete",
  "admin-brands-delete",
  "admin-taxonomy-delete",
  "admin-company",
  "admin-leads",
  "admin-session",
  "admin-events-core",
  "admin-events-products",
  "admin-events-brands",
  "admin-events-taxonomy",
  "admin-events-filters",
  "admin-events-company",
  "admin-init",
];

const banner = [
  "/*",
  " * Generated by scripts/build-admin.js.",
  " * Edit js/admin-*.js source modules, then run npm run build:admin.",
  " */",
].join("\n");

const chunks = adminModules.map((moduleName) => {
  const file = path.join(root, "js", `${moduleName}.js`);

  if (!fs.existsSync(file)) {
    throw new Error(`Missing admin module: ${path.relative(root, file)}`);
  }

  const source = fs
    .readFileSync(file, "utf8")
    .replace(/^\uFEFF/, "")
    .trimEnd();
  return `\n// ---- ${moduleName}.js ----\n${source}`;
});

fs.writeFileSync(outFile, `${banner}\n${chunks.join("\n")}\n`, "utf8");
console.log(`Built ${path.relative(root, outFile)} from ${adminModules.length} modules.`);
